name: Build and deploy React app to Azure Web App - shopping-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71AD8B956A454CAFB4551C92153A34CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C076C7530AB84118AF5B48182855E805 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2244BAED45204B77895A9281DF34B354 }}

      - name: Deploy build folder to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shopping-app'
          slot-name: 'Production'
          package: build
